In [1]:
import pandas as pd
import numpy as np
from INDOML.INDOML.model.supervised import DecisionTree 
from INDOML.INDOML.model.Ensemble import RandomForest 
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('seeds_dataset.csv',delimiter="\t")
df

Area  Perimeter  Compactness  Kernel_len  Kernel_width  Assymetry  \
0    15.26      14.84       0.8710       5.763         3.312      2.221   
1    14.88      14.57       0.8811       5.554         3.333      1.018   
2    14.29      14.09       0.9050       5.291         3.337      2.699   
3    13.84      13.94       0.8955       5.324         3.379      2.259   
4    16.14      14.99       0.9034       5.658         3.562      1.355   
..     ...        ...          ...         ...           ...        ...   
205  12.19      13.20       0.8783       5.137         2.981      3.631   
206  11.23      12.88       0.8511       5.140         2.795      4.325   
207  13.20      13.66       0.8883       5.236         3.232      8.315   
208  11.84      13.21       0.8521       5.175         2.836      3.598   
209  12.30      13.34       0.8684       5.243         2.974      5.637   

     Groove_len  Category  
0         5.220         1  
1         4.956         1  
2         4.825         1  
3         4.805         1  
4         5.175         1  
..          ...       ...  
205       4.870         3  
206       5.003         3  
207       5.056         3  
208       5.044         3  
209       5.063         3  

[210 rows x 8 columns]

In [3]:
X = df[df.columns[:-1]]
X

Area  Perimeter  Compactness  Kernel_len  Kernel_width  Assymetry  \
0    15.26      14.84       0.8710       5.763         3.312      2.221   
1    14.88      14.57       0.8811       5.554         3.333      1.018   
2    14.29      14.09       0.9050       5.291         3.337      2.699   
3    13.84      13.94       0.8955       5.324         3.379      2.259   
4    16.14      14.99       0.9034       5.658         3.562      1.355   
..     ...        ...          ...         ...           ...        ...   
205  12.19      13.20       0.8783       5.137         2.981      3.631   
206  11.23      12.88       0.8511       5.140         2.795      4.325   
207  13.20      13.66       0.8883       5.236         3.232      8.315   
208  11.84      13.21       0.8521       5.175         2.836      3.598   
209  12.30      13.34       0.8684       5.243         2.974      5.637   

     Groove_len  
0         5.220  
1         4.956  
2         4.825  
3         4.805  
4         5.175  
..          ...  
205       4.870  
206       5.003  
207       5.056  
208       5.044  
209       5.063  

[210 rows x 7 columns]

In [4]:
y = df[df.columns[-1]]
y

0      1
1      1
2      1
3      1
4      1
      ..
205    3
206    3
207    3
208    3
209    3
Name: Category, Length: 210, dtype: int64

In [5]:
X = X.to_numpy()
X

array([[15.26  , 14.84  ,  0.871 , ...,  3.312 ,  2.221 ,  5.22  ],
       [14.88  , 14.57  ,  0.8811, ...,  3.333 ,  1.018 ,  4.956 ],
       [14.29  , 14.09  ,  0.905 , ...,  3.337 ,  2.699 ,  4.825 ],
       ...,
       [13.2   , 13.66  ,  0.8883, ...,  3.232 ,  8.315 ,  5.056 ],
       [11.84  , 13.21  ,  0.8521, ...,  2.836 ,  3.598 ,  5.044 ],
       [12.3   , 13.34  ,  0.8684, ...,  2.974 ,  5.637 ,  5.063 ]])

In [6]:
y = y.to_numpy()
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [7]:
type(y[0])

numpy.int64

In [8]:
dt = DecisionTree(10)

In [9]:
dt.fit(X,y)

In [10]:
y_pred= dt.fit_predict(X,y)

In [11]:
dt.score_accuracy(y_pred,y)

1.0

In [12]:
rf = RandomForest(5,random_state=1304211035,n_tree=20)

In [13]:
X.shape

(210, 7)

In [14]:
pred = rf.fit_predict(X,y)
pred

model-1 akurasi : 0.9095238095238095 dan OOB error : 0.09047619047619049
model-2 akurasi : 0.8904761904761904 dan OOB error : 0.10952380952380958
model-3 akurasi : 0.8476190476190476 dan OOB error : 0.1523809523809524
model-4 akurasi : 0.9095238095238095 dan OOB error : 0.09047619047619049
model-5 akurasi : 0.9142857142857143 dan OOB error : 0.08571428571428574
model-6 akurasi : 0.9142857142857143 dan OOB error : 0.08571428571428574
model-7 akurasi : 0.919047619047619 dan OOB error : 0.080952380952381
model-8 akurasi : 0.919047619047619 dan OOB error : 0.080952380952381
model-9 akurasi : 0.919047619047619 dan OOB error : 0.080952380952381
model-10 akurasi : 0.8476190476190476 dan OOB error : 0.1523809523809524
model-11 akurasi : 0.9142857142857143 dan OOB error : 0.08571428571428574
model-12 akurasi : 0.919047619047619 dan OOB error : 0.080952380952381
model-13 akurasi : 0.8714285714285714 dan OOB error : 0.12857142857142856
model-14 akurasi : 0.9142857142857143 dan OOB error : 0.08571

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1,
       1, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 1, 3, 3,
       1, 1, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3])

In [15]:
rf.score_accuracy(pred,y)

0.9142857142857143

In [16]:
dts = DecisionTreeClassifier(max_depth=2)

In [17]:
dts.fit(X,y)

DecisionTreeClassifier(max_depth=2)

In [18]:
y_pred_sk = dts.predict(X)

In [19]:
dt.score_accuracy(y_pred_sk,y)

0.919047619047619